#!/usr/bin/env python3
"""Fill the analysis sections of TBK-TST-002 from the TBK-TST-001 results.

Run from the repo root, after tbk_tst_001_fit.py fit (and tp5):
    python docs/05-tests/tbk_tst_002_fill.py

Replaces the text between each <!-- auto:NAME --> and <!-- /auto:NAME --> marker in
TBK-TST-002-test-report.md:
    summary    the TP3, TP4 and TP5 rows of Table 1
    fit        fitted values with 95 % intervals, fit quality, energy balance, TP4 loss, Figure 1
    tp5        TP5 hourly comparison
    fullscale  TBK-CAL-001 re-run with the fitted sand, contact and stone wool values
Everything outside the markers is left alone. The document version is not changed: add a
revision row by hand before committing.

Options: --results DIR (default docs/05-tests/results), --out FILE (default: the report).
Licensed MIT (see LICENSE-SOFTWARE).
"""
import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPORT = HERE / "TBK-TST-002-test-report.md"


def ok(b):
    return "Pass" if b else "**Fail**"


def block_summary(fit, tp5):
    p = fit["pass"]
    r = fit["rms_K"]
    t80 = fit["t80_h"]
    lw = fit["loss_W"]
    rows = [
        f"| TP3 Charge | | Fitted RMS 10 K or less; time to 80 % within 10 %; power correction within 5 % | "
        f"RMS {r['fitted']:.1f} K; time to 80 % {t80['error'] * 100:+.1f} %; power correction "
        f"{(fit['params']['p_scale'] - 1) * 100:+.1f} % | "
        f"{ok(p['TP3_rms_le_10K'] and p['TP3_t80_within_10pct'] and p['power_correction_within_5pct'])} |",
        f"| TP4 Cool-down | | Loss at 450 °C within 20 % of 249 W before fitting | "
        f"{lw['fitted_at_450']:.0f} W ({lw['error'] * 100:+.1f} %) | {ok(p['TP4_loss_within_20pct'])} |",
    ]
    if tp5:
        scored = [h for h in tp5["hours"] if h["scored"] and h["error"] == h["error"]]
        worst = max((abs(h["error"]) for h in scored), default=float("nan"))
        rows.append(f"| TP5 Discharge | | Hourly duty within 15 % of the model, no refit | "
                    f"Worst hour {worst * 100:.1f} % over {len(scored)} hours | {ok(tp5['pass'])} |")
    else:
        rows.append("| TP5 Discharge | | Hourly duty within 15 % of the model, no refit | *not yet run* | |")
    return "\n".join(rows)


def block_fit(fit, fig=None):
    p, ci, r = fit["params"], fit["ci95"], fit["rms_K"]
    e, t80, lw = fit["energy_balance_tp3"], fit["t80_h"], fit["loss_W"]
    L = [f"The fit to {Path(fit['files']['tp3']).name} and {Path(fit['files']['tp4']).name} reproduces the three "
         f"thermocouples with an RMS error of {r['fitted']:.1f} K, against {r['unfitted']:.1f} K for the model with the "
         f"TBK-CAL-001 literature values (Table 10).", "",
         "| Property | Assumed (TBK-CAL-001) | Fitted | 95 % interval |", "| --- | --- | --- | --- |",
         f"| Sand conductivity multiplier | 1.00 | {p['k_sand']:.3f} | {ci['k_sand'][0]:.3f} to {ci['k_sand'][1]:.3f} |",
         f"| Wall contact conductance | 300 W/(m² K) | {p['h_contact']:.0f} W/(m² K) | "
         f"{ci['h_contact'][0]:.0f} to {ci['h_contact'][1]:.0f} W/(m² K) |",
         f"| Stone wool conductivity multiplier | 1.00 | {p['k_ins']:.3f} | {ci['k_ins'][0]:.3f} to {ci['k_ins'][1]:.3f} |",
         f"| Heater power correction | 1.00 | {p['p_scale']:.3f} | {ci['p_scale'][0]:.3f} to {ci['p_scale'][1]:.3f} |",
         "", "*Table 10. Fitted properties. The intervals come from the fit's Jacobian and are optimistic, because "
         "successive readings are correlated.*", "",
         "| Check | Result |", "| --- | --- |",
         f"| RMS error, T1 / T4 / T3 | {r['fitted_T1']:.1f} / {r['fitted_T4']:.1f} / {r['fitted_T3']:.1f} K |",
         f"| TP3 energy balance | Heater {e['heater_kWh']:.2f} kWh = stored {e['stored_from_temps_kWh']:.2f} kWh + loss "
         f"{e['loss_kWh']:.2f} kWh; closure {e['closure'] * 100:+.1f} % |",
         f"| Time to 80 % charge | Measured {t80['measured']:.2f} h, predicted {t80['predicted']:.2f} h "
         f"({t80['error'] * 100:+.1f} %) |",
         f"| Well-wall limit first reached | {fit['t_wall_limit_h']:.2f} h (TBK-CAL-002 predicts 2.1 h) |",
         f"| Standby loss, fitted | {lw['fitted_at_450']:.0f} W at 450 °C, {lw['fitted_at_300']:.0f} W at 300 °C, "
         f"{lw['fitted_at_150']:.0f} W at 150 °C (TBK-CAL-002: 249, 141 and 57 W) |",
         "", "*Table 11. Fit quality and derived results.*"]
    if fig:
        L += ["", f"![Measured temperatures against the fitted model through the charge and cool-down]({fig})", "",
              "*Figure 1. TP3 and TP4, measured (dashed) against the fitted model (solid). "
              "Generated by `tbk_tst_001_fit.py`.*"]
    return "\n".join(L)


def block_tp5(tp5):
    if not tp5:
        return "*TP5 not yet run. Run `python docs/05-tests/tbk_tst_001_fit.py tp5 --tp5 FILE`, then this script.*"
    L = [f"Predicted from {Path(tp5['file']).name} with the fitted values and no refit. {tp5['note']}", "",
         "| Hour | Measured (W) | Model (W) | Error |", "| --- | --- | --- | --- |"]
    for h in tp5["hours"]:
        err = f"{h['error'] * 100:+.1f} %" if h["error"] == h["error"] else "n/a"
        L.append(f"| {h['hour']}{'' if h['scored'] else ' (not scored)'} | {h['measured_W']:.0f} | "
                 f"{h['model_W']:.0f} | {err} |")
    L += ["", f"*Table 12. TP5 hourly exchanger duty. Result: {ok(tp5['pass'])}.*"]
    return "\n".join(L)


def block_fullscale(fit):
    """Re-run the full-scale charge, discharge and standby with the fitted values."""
    sys.path.insert(0, str(HERE.parent / "04-calcs"))
    import numpy as np
    import tbk_cal_001 as c        # full-scale geometry; tbk_cal_002 is never imported here
    p = fit["params"]

    def run():
        loss = lambda T: c.standby(T)["total"]  # noqa: E731
        lg = c.charge(loss=loss)["log"]
        t = np.array([r[0] for r in lg])
        T6 = float(np.interp(6, t, [r[4] for r in lg])) if t[-1] >= 6 else c.T_HI
        e6 = (c.h_sand(T6) - c.h_sand(c.T_LO)) / (c.h_sand(c.T_HI) - c.h_sand(c.T_LO)) * c.storage()["E"]
        dc = c.discharge(loss=loss)["log"]
        hold = next((r[0] for r in dc if r[1] < 990), dc[-1][0])
        return lg[-1][0], e6, hold, c.standby(450.0)["total"]

    base = run()
    k_mw0, h0 = c.k_mw, c.H_CONTACT
    c.K_SCALE, c.H_CONTACT = p["k_sand"], p["h_contact"]
    c.k_mw = lambda Tm: p["k_ins"] * k_mw0(Tm)
    try:
        new = run()
    finally:
        c.K_SCALE, c.H_CONTACT, c.k_mw = 1.0, h0, k_mw0
    r3 = "met" if new[0] <= 8.0 else "not met"
    L = ["TBK-CAL-001 re-run with the fitted sand conductivity, contact conductance and stone wool conductivity. "
         "The full-scale AES hot face was not tested, so its conductivity is unchanged.", "",
         "| Full-scale result | TBK-CAL-001 v0.2 | With fitted values |", "| --- | --- | --- |",
         f"| Time to full charge (R3: 8 h or less) | {base[0]:.1f} h | {new[0]:.1f} h |",
         f"| Heat stored in 6 h | {base[1]:.1f} kWh | {new[1]:.1f} kWh |",
         f"| 1.0 kW held for | {base[2]:.1f} h | {new[2]:.1f} h |",
         f"| Standby loss at 450 °C | {base[3]:.0f} W | {new[3]:.0f} W |",
         "", f"*Table 13. Full-scale predictions with the measured properties. R3 on the charge-time target: {r3}.*"]
    return "\n".join(L)


def replace(text, name, body):
    pat = re.compile(rf"(<!-- auto:{name} -->\n).*?(\n<!-- /auto:{name} -->)", re.S)
    if not pat.search(text):
        raise SystemExit(f"marker auto:{name} not found")
    return pat.sub(lambda m: m.group(1) + body + m.group(2), text)


def main():
    ap = argparse.ArgumentParser(description="Fill TBK-TST-002 from the analysis results")
    ap.add_argument("--results", default=str(HERE / "results"))
    ap.add_argument("--out", default=str(REPORT))
    ap.add_argument("--prefix", default="tbk_tst_001", help="results file prefix (selftest uses selftest/selftest)")
    a = ap.parse_args()
    res = Path(a.results)
    fit_p = res / f"{a.prefix}_fit.json"
    if not fit_p.exists():
        raise SystemExit(f"{fit_p} not found: run tbk_tst_001_fit.py fit first")
    fit = json.loads(fit_p.read_text())
    tp5_p = res / f"{a.prefix}_tp5.json"
    tp5 = json.loads(tp5_p.read_text()) if tp5_p.exists() else None
    text = REPORT.read_text(encoding="utf-8")
    text = replace(text, "summary", block_summary(fit, tp5))
    svg = res / f"{a.prefix}_fit.svg"
    fig = str(svg.resolve().relative_to(HERE)) if svg.exists() and HERE in svg.resolve().parents else None
    text = replace(text, "fit", block_fit(fit, fig))
    text = replace(text, "tp5", block_tp5(tp5))
    print("re-running TBK-CAL-001 with the fitted values ...")
    text = replace(text, "fullscale", block_fullscale(fit))
    Path(a.out).write_text(text, encoding="utf-8")
    print(f"wrote {a.out}. Add a revision row before committing.")


if __name__ == "__main__":
    main()
