#!/usr/bin/env python3
"""Generate docs/07-build/cut-list.md: every dimension the test article build needs.

Run from the repo root:  python docs/07-build/cutlist.py

All numbers come from cad/src/test_article.py, cad/src/enclosure.py and the schematic in
electronics/src/schematic.py, so the build procedure never carries its own dimensions.
Licensed MIT (see LICENSE-SOFTWARE).
"""
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "cad" / "src"))
sys.path.insert(0, str(ROOT / "electronics" / "src"))

import enclosure  # noqa: E402
import test_article as ta  # noqa: E402

P, D = ta.PARAMS, ta.derived()
E, ED = enclosure.PARAMS, enclosure.derived()
TC_HEIGHT = 300.0          # thermocouple tips above the inner drum floor (TBK-TST-001, Table 2)
PROBE = 500.0              # MI probe length
BATT = (387.0, 1194.0)     # 15.25 x 47 in stone wool batt
PACK_M2 = 59.7 * 0.0929    # one pack


def f(v, dp=0):
    return f"{v:,.{dp}f}"


def main():
    import csv
    bom = {r["item"]: r for r in csv.DictReader(open(ROOT / "bom" / "bom-test-article.csv", encoding="utf-8"))}
    packs = int(float(bom["Stone wool batt"]["qty"]))
    L = ["# Test article cut list", "",
         "Generated by `docs/07-build/cutlist.py` from `cad/src/test_article.py`, `cad/src/enclosure.py` and "
         "`electronics/src/schematic.py`. Do not edit; regenerate after any model change. Dimensions in mm. "
         "The build procedure (`test-article-build.md`) refers to the item numbers.", ""]

    # C1 wells
    L += ["## C1. Heater wells", "",
          f"Four pieces of 3/4 in black steel pipe, **{f(D['well_cut'])} mm** each, from one 10 ft (3,048 mm) stick. "
          f"Crimp the bottom 25 mm of each closed in a vise, leaving a finished well of {f(D['well_cut'] - 25)} mm. "
          f"The well bottom stands {f(P['well_floor_gap'])} mm above the inner drum floor and the top ends "
          f"{f(P['well_above_lid'])} mm above the lid.", ""]

    # C2 U-tube
    span = P["leg_span"]
    L += ["## C2. U-tube", "",
          "Two 1-1/4 in x 36 in black nipples (legs), two 1-1/4 in 90 degree elbows and one 1-1/4 in x 6 in nipple. "
          "No cutting.",
          f"Assembled, the leg centers are {f(span, 1)} mm apart and each leg top stands "
          f"{f(D['leg_above_jacket'])} mm above the jacket top. The bend centerline sits {f(P['bend_z'])} mm above "
          "the inner floor.", ""]

    # C3 lid holes
    L += ["## C3. Drum lid holes", "",
          "Measured from the lid center. Mark +x toward the front, where the controller will stand, before drilling.", "",
          "| Hole | x | y | Diameter | For |", "| --- | --- | --- | --- | --- |"]
    for k, (x, y) in enumerate(P["heater_xy"], 1):
        L.append(f"| W{k} | {f(x)} | {f(y)} | {f(P['well_od'] + 2, 1)} | Heater well W{k} |")
    L.append(f"| Inlet | 0 | {f(-span / 2, 1)} | {f(P['tube_od'] + 2, 1)} | U-tube inlet leg |")
    L.append(f"| Outlet | 0 | {f(span / 2, 1)} | {f(P['tube_od'] + 2, 1)} | U-tube outlet leg |")
    L += ["", "*Thermocouple probes pass through the headspace insulation beside wells W1 and W3 and at the "
          "center; drill three 4 mm holes in the lid at the C4 positions.*", ""]

    # C4 thermocouples
    x1, y1 = P["heater_xy"][0]
    x3, y3 = P["heater_xy"][2]
    r1 = math.hypot(x1, y1)
    th = math.atan2(y1, x1)
    face = r1 + P["well_od"] / 2
    tip_z = D["floor_z"] + TC_HEIGHT
    top_gap = D["jacket_top_z"] - (tip_z + PROBE)
    rows = [("T1", "Well W1 outer face (control)", face * math.cos(th), face * math.sin(th)),
            ("T2", "Well W3 outer face (limit)", -face * math.cos(th), -face * math.sin(th)),
            ("T3", "Sand, drum axis", 0.0, 0.0),
            ("T4", "Sand on the W1 ray, 20 mm from the drum wall", 151 * math.cos(th), 151 * math.sin(th))]
    L += ["## C4. Thermocouple positions", "",
          f"Tips **{f(TC_HEIGHT)} mm above the inner drum floor**, all four. With {f(PROBE)} mm probes the probe top "
          f"ends {f(top_gap)} mm below the jacket top, inside the top insulation, so the lead junction stays cool.", "",
          "| Tag | Location | x | y |", "| --- | --- | --- | --- |"]
    L += [f"| {t} | {w} | {f(x)} | {f(y)} |" for t, w, x, y in rows]
    L += ["", "T5 goes 50 mm inside the top of the outlet leg; T6 hangs 300 mm from the blower intake.", ""]

    # C5 sand
    L += ["## C5. Sand", "",
          f"{f(P['sand_mass_kg'])} kg of dry washed sand, filled to **{f(D['sand_depth'])} mm above the inner floor** "
          f"({f(D['sand_vol_m3'] * 1000, 1)} L). Mark the level on the inside of the drum wall before filling. "
          f"The headspace above it is {f(D['ins_top_int'])} mm.", ""]

    # C6 base
    bl, bw, bh = P["brick"]
    L += ["## C6. Base", "",
          f"Four K-23 bricks stood on edge ({f(bl)} x {f(bw)} x {f(bh)}), radial at 45, 135, 225 and 315 degrees, "
          f"centered {f(P['brick_r'])} mm from the drum axis (inner ends {f(P['brick_r'] - bl / 2)} mm, outer ends "
          f"{f(P['brick_r'] + bl / 2)} mm). The drum chime bears across each brick. Pack stone wool between the bricks "
          f"to the full base diameter of {f(2 * D['jacket_r_i'])} mm.", ""]

    # C7 to C9 insulation
    area = 0.0
    L += ["## C7. Headspace insulation", "",
          f"Two discs of stone wool, {f(P['drum_id'])} mm diameter, stacked to {f(D['ins_top_int'])} mm. Cut holes for "
          "the four wells, both legs and three thermocouple probes at the C3 and C4 positions.", ""]
    area += 2 * math.pi * (P["drum_id"] / 2000) ** 2
    L += ["## C8. Side insulation", "",
          f"Three layers of 89 mm batt around the drum, {f(D['jacket_top_z'] - P['base_h'])} mm tall "
          f"(base to jacket top). Butt the joints and stagger them between layers.", "",
          "| Layer | Inner radius | Wrap length at mid-thickness | Batt pieces (387 wide) |", "| --- | --- | --- | --- |"]
    h_side = D["jacket_top_z"] - P["base_h"]
    for k in range(3):
        ri = D["drum_r_o"] + 89 * k
        wrap = 2 * math.pi * (ri + 44.5)
        pieces = math.ceil(wrap / BATT[0]) * math.ceil(h_side / BATT[1])
        area += wrap / 1000 * h_side / 1000
        L.append(f"| {k + 1} | {f(ri)} | {f(wrap)} | {pieces} pieces of {f(BATT[0])} x {f(min(h_side, BATT[1]))} |")
    top_d = 2 * D["drum_r_o"]
    area += 2 * math.pi * (top_d / 2000) ** 2
    # base: full disc to the base height, less the four bricks, in batt thicknesses of 89 mm
    bl_, bw_, bh_ = P["brick"]
    base_area = math.pi * (D["jacket_r_i"] / 1000) ** 2 - P["n_bricks"] * bl_ * bw_ / 1e6
    area += base_area * P["base_h"] / 89.0
    L += ["", "## C9. Top insulation", "",
          f"Two discs of 89 mm batt, {f(top_d)} mm diameter, over the lid, to {f(P['ins_top'])} mm. Slit for the legs, "
          "heater leads and thermocouple probes.", "",
          f"*Batt check: about {f(area, 2)} m2 of 89 mm batt is needed (headspace, side, top and base) against "
          f"{f(PACK_M2, 2)} m2 in one pack"
          + f". The BOM lists {packs} pack{'s' if packs > 1 else ''} ({f(packs * PACK_M2, 2)} m2)"
          + (".*" if area <= packs * PACK_M2 else f", {f(area - packs * PACK_M2, 2)} m2 short: add a pack.*"), ""]

    # C10 jacket
    rj = D["jacket_r_o"]
    wrap = 2 * math.pi * rj + 50
    L += ["## C10. Jacket", "",
          f"Aluminum flashing, 508 mm (20 in) wide. Side: two rows, each {f(wrap)} mm long (includes 50 mm overlap), "
          f"lapped 50 mm where they meet; total height {f(D['jacket_top_z'])} mm, trim the top row to fit. "
          f"Top cap: a {f(2 * rj + 30)} mm disc from two overlapped strips, with a 15 mm turned-down edge, and holes for "
          f"both legs ({f(P['tube_od'] + 2, 1)} mm), the heater leads and the thermocouple leads. "
          f"Flashing used: about {f((2 * wrap + 2 * (2 * rj + 30)) / 1000, 1)} m of the 7.6 m roll.", ""]

    # C11 enclosure
    W, H = E["width"], E["height"]
    rx, rz = E["rex_xz"]
    L += ["## C11. Controller enclosure", "",
          f"Lid, measured from its bottom-left corner seen from the front ({f(W)} x {f(H)} lid):", "",
          "| Cutout | x | z | Size |", "| --- | --- | --- | --- |",
          f"| REX-C100 | {f(W / 2 + rx)} | {f(rz)} | {f(E['rex_cutout'])} x {f(E['rex_cutout'])} square (center) |"]
    for name, key in (("STOP", "stop_xz"), ("START", "start_xz")):
        bx, bz = E[key]
        L.append(f"| {name} | {f(W / 2 + bx)} | {f(bz)} | {f(E['button_hole'], 1)} diameter |")
    L += ["", f"Bottom face, holes on a line {f(E['depth'] / 2)} mm back from the lid face, x from the left end:", "",
          "| Gland | x | Hole |", "| --- | --- | --- |"]
    for label, thread, gx in E["glands"]:
        L.append(f"| M{f(thread)} {label} | {f(W / 2 + gx)} | {f(thread + 0.5, 1)} diameter |")
    x1r, x2r = E["rail_x"]
    L += ["", f"DIN rail: cut to {f(x2r - x1r)} mm, fixed to the mounting plate {f(E['rail_z'] - E['wall'] - E['plate_margin'])} mm "
          "up from the plate's bottom edge, starting at its left edge.", ""]

    # C12 wiring list from the schematic
    import schematic as S
    L += ["## C12. Wiring list", "",
          "Every connection on TBK-DWG-003, generated from `electronics/src/schematic.py`. Mains nets (L_, N, PE and "
          "heater nets) in 16 AWG, 105 C rated, except the cord to F1 in 14 AWG; low-voltage nets in 22 AWG.", "",
          "| Net | Connects |", "| --- | --- |"]
    nets = S.expected_nets()
    mains = [n for n in nets if n.startswith("L_") or n in ("N", "PE")]
    for n in sorted(mains) + sorted(x for x in nets if x not in mains):
        L.append(f"| {n} | {', '.join(sorted(nets[n]))} |")
    L.append("")
    (HERE / "cut-list.md").write_text("\n".join(L), encoding="utf-8")
    print(f"wrote docs/07-build/cut-list.md (batt area {area:.2f} m2 of {PACK_M2:.2f})")


if __name__ == "__main__":
    main()
